@HostAddress = http://localhost:5222/v1

### Get game types

GET {{HostAddress}}/gameType
Accept: application/json

### Get game sessions

GET {{HostAddress}}/gameSession
Accept: application/json

### Create game session

POST {{HostAddress}}/gameSession?gameType=Hearts
Accept: application/json

> {% client.global.set("SessionId", response.body.sessionId); %}

### Get game state and new events

GET {{HostAddress}}/gameSession/{{SessionId}}
Accept: application/json

### Play card

POST {{HostAddress}}/GameSession/{{SessionId}}/playCard
Accept: application/json

{
    "IndexOfCardToPlay": 0
}

### Play cards

POST {{HostAddress}}/GameSession/{{SessionId}}/playCards
Accept: application/json

{
    "IndexesOfCardsToPlay": [
    ]
}
