@HostAddress = http://localhost:5222

### Get game types

GET {{HostAddress}}/gameType
Accept: application/json

### Get game sessions

GET {{HostAddress}}/gameSession
Accept: application/json

### Create game session

POST {{HostAddress}}/gameSession?gameType=Hearts
Accept: application/json

> {% client.global.set("SessionId", response.body.sessionId); %}

### Get new game events

GET {{HostAddress}}/gameSession/{{SessionId}}/newEventsSince/{{LastEventId}}
Accept: application/json

> {% client.global.set("LastEventId", response.body.lastEventsId); %}

### Play card

# TODO: this

### Play cards

# TODO: this
